### PR TITLE
Fix cuda kernel for Pascal & Cuda 6/6.1

### PR DESCRIPTION
**Pull request by Ph0rk0z**
When I left the other functions to use normal atomic add it seemed like a small speedup. 4.79 it/s vs 5.23 it/s

It works by just changing the parameter to _half though.

### CODE REVIEW

**Comment by johnsmith0031** [comment]
Thanks you!

**Comment by wywywywy** [comment]
@Ph0rk0z @johnsmith0031 

Is line 634 supposed to say 

```c++
atomicAdd(&mul2[n_cols * height * 8 + n_rows], res);
``` 
rather than 
```c++
atomicAddHalf(&mul2[n_cols * height * 8 + n_rows], res);
```
?

**Comment by johnsmith0031** [comment]
Yes just fixed it.

**Comment by Ph0rk0z** [comment]
Ooops!

**Pull request merged**
